// App state: the core engine's items/series + settings + UI state, persisted on-device.
// All scheduling rules live in @simpleapp/core; this file only wires them to React.

import AsyncStorage from '@react-native-async-storage/async-storage';
import {
  applyEdit, applyOps, collectPush, fmtDate, handleInputWithFallback, markAllDirty, markChanges, markPushed, mergeRemote,
  refreshSeries, requestDelete, toggleTask,
  type Choice, type ClaimMoment, type CoreSettings, type EditFields, type EngineContext, type EngineState,
  type Item, type Jump, type Outcome, type Series, type SyncData, type SyncMeta,
} from '@simpleapp/core';
import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { AppState, useColorScheme } from 'react-native';

import { supabase } from '../auth/supabase';
import { currentUserId, pull, push } from './syncClient';
import { useNotifications } from './useNotifications';

import { aiAllowed, fetchFallbackIntent, isFallbackConfigured } from './fallbackClient';
import { palettes, type Palette } from '../theme';

export type CalView = 'day' | 'week' | 'month';

export interface Settings extends CoreSettings {
  theme: 'system' | 'dark' | 'light';
  colorCode: boolean;
  hideCompletedNextDay: boolean;
}

export const DEFAULT_SETTINGS: Settings = {
  theme: 'system',
  defaultDuration: 30,
  eventAlerts: [15],
  colorCode: true,
  hideCompletedNextDay: true,
};

interface Persisted {
  version: 1;
  items: Item[];
  series: Series[];
  settings: Settings;
  dismissed: ClaimMoment[];
}

export interface Message {
  id: number;
  text: string;
  choices: Choice[];
  jump: Jump | null;
}

const STORAGE_KEY = 'simpleapp:v1';
const SYNC_KEY = 'simpleapp:sync:v1';

interface SyncPersisted {
  meta: SyncMeta;
  /** Server time of the newest change we've pulled. */
  cursor: string | null;
  /** Account the meta/cursor belong to. A different account => upload everything once. */
  userId: string | null;
}
const EMPTY_SYNC: SyncPersisted = { meta: {}, cursor: null, userId: null };

function newId(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c?.randomUUID) return c.randomUUID();
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (ch) => {
    const r = (Math.random() * 16) | 0;
    return (ch === 'x' ? r : (r & 0x3) | 0x8).toString(16);
  });
}

/** Ticks every 30s so "today", rollover and greetings stay current. */
function useNow(): Date {
  const [now, setNow] = useState(() => new Date());
  useEffect(() => {
    const t = setInterval(() => setNow(new Date()), 30_000);
    return () => clearInterval(t);
  }, []);
  return now;
}

function useStoreValue() {
  const now = useNow();
  const systemScheme = useColorScheme();
  const [loaded, setLoaded] = useState(false);
  const [engine, setEngine] = useState<EngineState>({ items: [], series: [], pending: null });
  const [settings, setSettingsState] = useState<Settings>(DEFAULT_SETTINGS);
  const [dismissed, setDismissed] = useState<ClaimMoment[]>([]);
  const [message, setMessage] = useState<Message | null>(null);
  const [busy, setBusy] = useState(false);
  const [calView, setCalView] = useState<CalView>('day');
  const [viewDate, setViewDate] = useState(() => fmtDate(new Date()));
  const [editingId, setEditingId] = useState<string | null>(null);
  const [pendingTab, setPendingTab] = useState<Jump['tab'] | null>(null);

  // Latest values for async callbacks.
  const engineRef = useRef(engine);
  engineRef.current = engine;
  const settingsRef = useRef(settings);
  settingsRef.current = settings;
  const msgSeq = useRef(0);
  const syncRef = useRef<SyncPersisted>(EMPTY_SYNC);
  /** Last items/series the sync bookkeeping has seen; diffs against it find local edits. */
  const snapshotRef = useRef<SyncData | null>(null);
  const syncing = useRef(false);
  const syncTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [lastSyncedAt, setLastSyncedAt] = useState<Date | null>(null);
  const [syncError, setSyncError] = useState<string | null>(null);

  const ctx = useCallback((): EngineContext => ({ now: new Date(), settings: settingsRef.current, newId }), []);

  // Load once, then extend recurring series' rolling window.
  useEffect(() => {
    (async () => {
      try {
        const rawSync = await AsyncStorage.getItem(SYNC_KEY);
        if (rawSync) syncRef.current = { ...EMPTY_SYNC, ...(JSON.parse(rawSync) as SyncPersisted) };
        const raw = await AsyncStorage.getItem(STORAGE_KEY);
        if (raw) {
          const p = JSON.parse(raw) as Persisted;
          const loadedState: EngineState = { items: p.items ?? [], series: p.series ?? [], pending: null };
          // Occurrences generated by refreshSeries below count as local changes.
          snapshotRef.current = { items: loadedState.items, series: loadedState.series };
          const c: EngineContext = { now: new Date(), settings: { ...DEFAULT_SETTINGS, ...p.settings }, newId };
          setEngine(applyOps(loadedState, refreshSeries(loadedState, c)));
          const { homeMode: _dropped, ...saved } = p.settings as Settings & { homeMode?: unknown };
          setSettingsState({ ...DEFAULT_SETTINGS, ...saved });
          setDismissed(p.dismissed ?? []);
        }
      } catch {
        // Corrupt or unavailable storage: start fresh rather than crash.
      } finally {
        setLoaded(true);
      }
    })();
  }, []);

  // Persist (debounced) after load.
  useEffect(() => {
    if (!loaded) return;
    const t = setTimeout(() => {
      const p: Persisted = { version: 1, items: engine.items, series: engine.series, settings, dismissed };
      AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(p)).catch(() => {});
    }, 250);
    return () => clearTimeout(t);
  }, [loaded, engine.items, engine.series, settings, dismissed]);

  const persistSync = useCallback(() => {
    AsyncStorage.setItem(SYNC_KEY, JSON.stringify(syncRef.current)).catch(() => {});
  }, []);

  /** Push local changes, then pull everyone else's. Safe to call any time; no-ops offline. */
  const syncNow = useCallback(async () => {
    if (!supabase || syncing.current) return;
    syncing.current = true;
    try {
      const uid = await currentUserId();
      if (!uid) return;
      const data = (): SyncData => ({ items: engineRef.current.items, series: engineRef.current.series });
      if (syncRef.current.userId !== uid) {
        // New account on this device (e.g. anonymous account just created, or signed in):
        // upload everything here and read everything there.
        syncRef.current = { meta: markAllDirty(data(), syncRef.current.meta, new Date().toISOString()), cursor: null, userId: uid };
      }
      const batch = collectPush(data(), syncRef.current.meta);
      if (batch.items.length || batch.series.length) {
        await push(batch);
        syncRef.current = { ...syncRef.current, meta: markPushed(syncRef.current.meta, batch) };
      }
      const pulled = await pull(syncRef.current.cursor);
      const merged = mergeRemote(data(), syncRef.current.meta, pulled.rows);
      if (merged.changed) {
        snapshotRef.current = merged.data; // so these aren't mistaken for local edits
        setEngine((st) => ({ ...st, items: merged.data.items, series: merged.data.series }));
      }
      syncRef.current = { ...syncRef.current, meta: merged.meta, cursor: pulled.cursor };
      persistSync();
      setLastSyncedAt(new Date());
      setSyncError(null);
    } catch (e) {
      // Offline or server hiccup: changes stay queued and go out on the next attempt.
      setSyncError(e instanceof Error ? e.message : String(e));
    } finally {
      syncing.current = false;
    }
  }, [persistSync]);

  const scheduleSync = useCallback((delay = 1500) => {
    if (syncTimer.current) clearTimeout(syncTimer.current);
    syncTimer.current = setTimeout(() => void syncNow(), delay);
  }, [syncNow]);

  // Record local edits as dirty whenever items/series change.
  useEffect(() => {
    if (!loaded) return;
    const current: SyncData = { items: engine.items, series: engine.series };
    const prev = snapshotRef.current;
    snapshotRef.current = current;
    if (!prev || (prev.items === current.items && prev.series === current.series)) return;
    syncRef.current = { ...syncRef.current, meta: markChanges(prev, current, syncRef.current.meta, new Date().toISOString()) };
    persistSync();
    scheduleSync();
  }, [loaded, engine.items, engine.series, persistSync, scheduleSync]);

  // Sync on launch, on sign-in/out, when the app comes to the foreground, and every minute.
  useEffect(() => {
    if (!loaded || !supabase) return;
    void syncNow();
    const { data: sub } = supabase.auth.onAuthStateChange((event) => {
      if (event === 'SIGNED_IN' || event === 'USER_UPDATED') scheduleSync(0);
    });
    const appState = AppState.addEventListener('change', (st) => { if (st === 'active') scheduleSync(0); });
    const interval = setInterval(() => void syncNow(), 60_000);
    return () => { sub.subscription.unsubscribe(); appState.remove(); clearInterval(interval); };
  }, [loaded, syncNow, scheduleSync]);

  /** After signing out: this device forgets the account's data (it's safe on the server). */
  const clearLocalData = useCallback(() => {
    snapshotRef.current = { items: [], series: [] };
    syncRef.current = EMPTY_SYNC;
    persistSync();
    setEngine({ items: [], series: [], pending: null });
    setMessage(null);
  }, [persistSync]);

  const apply = useCallback((o: Outcome) => {
    setEngine((s) => ({ ...applyOps(s, o.ops), pending: o.pending }));
    setMessage(o.message ? { id: ++msgSeq.current, text: o.message, choices: o.choices, jump: o.jump } : null);
  }, []);

  const submit = useCallback(async (text: string) => {
    setBusy(true);
    try {
      const o = await handleInputWithFallback(engineRef.current, text, ctx(), {
        // If the device is actually offline the request fails fast and the rule result is used.
        online: isFallbackConfigured(),
        aiAllowed: aiAllowed(new Date()),
        fetchIntent: fetchFallbackIntent,
      });
      apply(o);
    } finally {
      setBusy(false);
    }
  }, [apply, ctx]);

  const choose = useCallback((c: Choice) => submit(c.reply), [submit]);

  const dismissMessage = useCallback(() => {
    setMessage(null);
    setEngine((s) => ({ ...s, pending: null }));
  }, []);

  const toggle = useCallback((id: string) => apply(toggleTask(engineRef.current, id, ctx())), [apply, ctx]);

  const saveEdit = useCallback((id: string, fields: EditFields) => {
    apply(applyEdit(engineRef.current, id, fields, ctx()));
    setEditingId(null);
  }, [apply, ctx]);

  const deleteItem = useCallback((id: string) => {
    apply(requestDelete(engineRef.current, id, ctx()));
    setEditingId(null);
  }, [apply, ctx]);

  const jump = useCallback((j: Jump) => {
    setMessage(null);
    if (j.date) {
      setViewDate(j.date);
      setCalView('day');
    }
    setPendingTab(j.tab);
  }, []);

  const notificationPermission = useNotifications(engine.items, settings, now, jump);

  const setSettings = useCallback((patch: Partial<Settings>) => setSettingsState((s) => ({ ...s, ...patch })), []);
  const dismissClaim = useCallback((m: ClaimMoment) => setDismissed((d) => (d.includes(m) ? d : [...d, m])), []);

  const scheme: 'dark' | 'light' = settings.theme === 'system' ? (systemScheme === 'light' ? 'light' : 'dark') : settings.theme;
  const palette: Palette = palettes[scheme];

  return {
    loaded, now, engine, settings, palette, scheme, message, busy, calView, viewDate, editingId, dismissed, pendingTab,
    lastSyncedAt, syncError, syncNow, clearLocalData,
    notificationPermission,
    submit, choose, dismissMessage, toggle, saveEdit, deleteItem, jump, setSettings, dismissClaim,
    setCalView, setViewDate, setEditingId, clearPendingTab: () => setPendingTab(null),
  };
}

export type Store = ReturnType<typeof useStoreValue>;
const StoreContext = createContext<Store | null>(null);

export function StoreProvider({ children }: { children: ReactNode }) {
  const value = useStoreValue();
  return <StoreContext.Provider value={value}>{children}</StoreContext.Provider>;
}

export function useStore(): Store {
  const s = useContext(StoreContext);
  if (!s) throw new Error('useStore outside StoreProvider');
  return s;
}
